src/components/Home/Home.js

What if there was an English major who could have made us world champions, but they refused to join because of that grammar mistake?

Fix grammar mistake

---

package-lock.json
package.json
src/App.js
src/components/About/About.js
src/components/Navbar/Navbar.js

Featuring an overview and a timeline using
vertical-timeline-component-for-react
(https://github.com/veysiyildiz/vertical-timeline-component-for-react).

Add an About page

---

src/components/About/About.js
src/components/About/timeline.json

About page now stores timeline events in a json file. Many thanks to
Meta for help with Javascript.

Refactor About page

---

package-lock.json
package.json
src/components/Home/Home.js

Add a small Konami code easter egg

---

src/components/About/About.js

Small change on the About page.

Expand abbreviation of ACM

---

src/components/About/About.js

The description now contains more info about the club.

Update about page description

---

src/App.js

Added a BrowserRouter to React Router to remove the '#' that appears in
paths otherwise.
[ ] @jens321 and @MetaNovitia please check to make sure I did not cause any chaos.
[ ] @MetaNovitia You may need to update the acm-uci.org link if you accept this.

Remove '#' from URLs

---

src/App.js
src/index.js
src/scss/custom.css

Technically, HashRouter's are better if we are only serving static
pages, but if we care a lot about removing the hash from the URL,
switching to a BrowserRouter should to the trick.

Removing the Hash Part 2

---

src/components/Board/board.json

:D
Never letting go of Director of Innovation.

Fix Bryon board position

---

.github/workflows/build.yaml
.github/workflows/deploy.yaml

Use GitHub Actions to handle CI/CD
N/A

Add workflows for building and deploying

---

.gitignore

Put categories in the gitignore and added ignoring of vim editor files (`*.swp`)

Rearrange gitignore

---

src/components/Blog/BlogPages/IEEExtreme13.js
src/scss/custom.css

Pretty straightforward. Just checking I did the links right.

Add link to IEEExtreme results

---

src/components/Blog/BlogPages/IEEExtreme13.js

Updating ieeextreme rankings to the official rankings

update ieeextreme rankings

---

src/components/About/About.js
src/components/Home/Home.js
src/components/Resources/Puzzle/Puzzle.js
src/scss/custom.css

Edit some descriptions about ACM@UCI, and add a help msg to the Problems page subtitle. The Home page description was a bit lengthy and had some grammar issues. The About page description was a bit outdated. The Problems page should now tell people about when the problems and solutions are available. Pretty small change overall.
- Are you okay with the Problems page subtitle spilling onto two lines?

Edit text on About, Home, Puzzle pages

---

src/components/Board/board.json

Pass on the everlasting torch of Director of Innovation to Agent Brian Chu.

Pass on Director of Innovation

---

src/components/Events/Events.js

Added link to google form for internal competition signup

Added link to google form for sign up for internal comp

---

src/components/Login/Auth.js
src/components/Login/Login.js

Fixed the authentication security issue. Session management is handled by firebase now. Prevents users from emulating other users. Also generalized authentication functionality so that it can be applied elsewhere.

Authentication fix

---

src/App.js
src/components/Blog/Blog.js
src/components/Blog/BlogMarkdownRenderers.js
src/components/Blog/BlogPage.js
src/components/Blog/CreateBlog.js
src/components/Blog/README.md
src/components/Blog/SubmitBlog.js
src/components/Blog/UploadBlog.js
src/components/Login/Login.js
src/index.js

Added UI functionality for creating new blog posts. This is restricted only to logged in users and it should be impossible to bypass this requirement. Uses can either design a post from the web interface or upload a markdown file of their post.

Blog submit

---

src/components/Login/Data/Data.js
src/components/Login/Data/Entry/Entry.js
src/components/Login/Login.js
src/components/Login/Submit/Submit.js
src/components/Resources/Puzzle/Past/Past.js
src/components/Resources/Puzzle/Puzzle.js
src/components/Resources/Puzzle/Quarter/Quarter.js
src/components/config.js
src/utils/Scheduling.js

Updated how quarter/week/session are determined allowing more flexible configuration of meeting times, durations, and number of meetings per week.
Computation of scheduling related information is now centralized to src/utils/Scheduling.js.
* components/Puzzle - Problems are rendered appropriately according to the scheduling configurations. A week can now have a variable number of sessions.
* components/Login - When adding problems to sessions the available sessions to add the problem to are limited by what is defined in components/config.js. Additional error detection has been added in the case the clock is inproperly set.
* components/config.js - Added new class Meetings which defines a meeting based on a start time and a duration.
* Problems submitted by a user were blocked from that …

Scheduling Changes:

---

src/components/Login/Data/Data.js
src/components/Login/Data/Entry/Entry.js
src/components/Login/Data/Entry/filter.js
src/components/Login/Login.js
src/components/Login/Submit/Submit.js
src/components/Resources/Puzzle/Past/Past.js
src/components/Resources/Puzzle/Present/Present.js
src/components/Resources/Puzzle/Puzzle.js
src/components/Resources/Puzzle/Quarter/Quarter.js
src/components/Resources/Puzzle/Quarter/Week/Session/Presentation/Presentation.css
src/components/Resources/Puzzle/Quarter/Week/Session/Presentation/Presentation.js
src/components/Resources/Puzzle/Quarter/Week/Session/Session.js
src/components/config.js
src/utils/Scheduling.js

Allows board members to add presentation links which will show up in the puzzle section. This is hopefully a temporary fix and an updated system can replace this.

Presentation links

---

src/components/Events/Competitions/UCIxUCSD/EditorialDeadlineDash.js
src/components/Events/Competitions/UCIxUCSD/EditorialICaughtTheBomber.js
src/data/ayrco.cpp
src/data/ayrco.py
src/data/deadline_dash.cpp
src/data/deadline_dash.py
src/data/i_caught_the_bomber.cpp
src/data/i_caught_the_bomber.py
src/data/mansion.py
src/data/shopping_cart_speedrun_100_wr.cpp
src/data/shopping_cart_speedrun_100_wr.py
src/data/toilet_paper_travesty.cpp

Added My Editorials

---

src/components/Events/Competitions/UCIxUCSD/EditorialAyrco.js
src/components/Events/Competitions/UCIxUCSD/EditorialMansion.js
src/components/Events/Competitions/UCIxUCSD/EditorialShoppingSpeedrun.js
src/data/mansion.cpp
src/data/shopping_cart_speedrun_100_wr.py

Ayrco, Mansion, Speedrun Editorials

---

src/components/Resources/IntroCP/IntroCP.js

Change the POV from I (Bryon) to We. This thing is taking on a life of its own, and besides, there are already parts that I did not write.
Notable points that this PR has either accomplished or will accomplish.

Make intro tutorial point-of-view more general
